[package]
name = "btc_hs"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.18", features = ["derive"] }
rand = "0.8.5"
sha2 = "0.10.8"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
